### ISSUE TITLE
Домашка №1, HTML

### ISSUE THREAD

**Issue by tiny-kottan** [Kilmyashkin/kottans#2]
Разметить эту страницу: https://habrahabr.ru/post/244929/
от вас ожидаеться `.html` файл с семантичной разметкой, без css/js
крупные части контента копипастить не стоит (саму статью, там `h*`/`p`/`code` -- все просто), а вот остальное -- нужно
как должно выглядить

`````` html
<!doctype html>
<html lang=ru>
<meta charset=utf-8>
<title>Habrahabr.ru</title>
<header>
  <ul>
    <li><a href=...>TM Feed</a>
    <li><a>Хабрахабр</a>
  </ul>```
``````

**Comment by Kilmyashkin** [comment]
https://github.com/Kilmyashkin/kottans/blob/master/week01/week01-1/index.html

**Comment by mkozhukharenko** [comment]
that is the sense in having firs't element hidden? 
https://github.com/Kilmyashkin/kottans/blob/master/week01/week01-1/index.html#L10

**Comment by mkozhukharenko** [comment]
https://github.com/stasgavrylov/kottans/blob/master/hw1/index.html#L10-L37
I would not use put element inside a `nav`
read [this](http://html5doctor.com/avoiding-common-html5-mistakes/#nav-external) to find out how to use this element properly

**Comment by mkozhukharenko** [comment]
you don't need form here
https://github.com/Kilmyashkin/kottans/blob/master/week01/week01-1/index.html#L99-L103
try to use an `a` element (since there should be a link) with a role=btn

**Comment by mkozhukharenko** [comment]
don't use section as a wrapper https://github.com/Kilmyashkin/kottans/blob/master/week01/week01-1/index.html#L144  (if it has not semantic meaning)

[read this to find more info](http://html5doctor.com/avoiding-common-html5-mistakes/#section-wrapper)

**Comment by mkozhukharenko** [comment]
I wouldn't wrap this content in a article
https://github.com/Kilmyashkin/kottans/blob/master/week01/week01-1/index.html#L169-L175
looks like it's used as a wrapper

**Comment by mkozhukharenko** [comment]
can it be a nav, what do you think? https://github.com/Kilmyashkin/kottans/blob/master/week01/week01-1/index.html#L198-L201

**Comment by mkozhukharenko** [comment]
``` html
          <figure>
            <meter value="0.0" max="1000">0,0</meter>
            <figcaption>Рейтинг</figcaption>
          </figure>
```

it doesn't work (
![image](https://cloud.githubusercontent.com/assets/9365923/15551517/03f48cde-22bf-11e6-9514-cef993c33db2.png)

**Comment by Kilmyashkin** [comment]
@mkozhukharenko 
Thank you for your feedback.
It is very helpful for me.
1. There are 2 unordered lists. One of them with the title. I have decided to create hidden title for another list. I think it will result in more readable code.
2. I agree with you. But it's not my html)
3. It makes sense, I have fixed it.
4. It's not a wrapper. "Comments" is a semantic section of my page.
5. According to W3C every independent item of a content can be an article. https://www.w3.org/TR/html5/sections.html#the-article-element 
It seems like all of "MOST POPULAR" articles are used as independent item. Also it seems logical when I use element "article" for an item called article)) 
6. "Register" and "sign in" links are the most important. Therefore, I guess you are right that they should be wrapped into "nav".
7. Seems it does not work. But it's because the default value of the meter is 0. If I change this value you will see that the meter works.
<img width="454" alt="2016-05-29 20 21 38" src="https://cloud.githubusercontent.com/assets/10762065/15635398/3f6207b8-25e6-11e6-9b6a-ce73d35a240e.png">

**Comment by mkozhukharenko** [comment]
> 1. I agree with you. But it's not my html)

https://github.com/Kilmyashkin/kottans/blob/master/week01/week01-1/index.html#L33-L57
what is about yours? 😸

**Comment by mkozhukharenko** [comment]
> 1. It's not a wrapper. "Comments" is a semantic section of my page.

You are right

**Comment by mkozhukharenko** [comment]
> 1. According to W3C every independent item of a content can be an article. 

you are right as well. I might misunderstand something.

**Comment by mkozhukharenko** [comment]
> 1. Seems it does not work. But it's because the default value of the meter is 0. If I change this value you will see that the meter works.

do you have any ideas how to style it properly?
